spring.application.name=flight-backend
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flight_Booking_System
spring.datasource.username=postgres
spring.datasource.password=Spoorthi@2005
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=flight_booking_system
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=1e561ab13dc3ac0ba177c453aba2e676a895ce13169eed7682e3479762ffb3f7
jwt.access.expiration=900000
jwt.refresh.expiration=604800000
jwt.cookie.name=refreshToken
jwt.cookie.secure=false
jwt.cookie.same-site=Lax
jwt.cookie.path=/

# Google OAuth2 Configuration
google.client.id=92274469042-idom1lfs8nhao9hbs4i6jofla6rpopqu.apps.googleusercontent.com